data_path: data/ml-1m/
project_path: ../

dataset:
  user_col: user_id
  item_col: item_id
  relevance_col: rating
  relevance_threshold: 4
  max_length: 100
  only_positive: True

dataloader:
  batch_size: 100
  test_batch_size: 500
  num_workers: 8
  validation_size: 100
  seed: 42

trainer_params:
  max_epochs: 100

patience: 10

model:
  dropout: 0.2
  hidden_units: 512
  lr: 0.0005
  num_blocks: 3
  barlow_coeff: 0.25
  off_diag_coeff: 0.005
  power_coef: 0.97
